[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip3 install -r requirements.txt"]

[start]
cmd = "python3 -m uvicorn bot.main:app --host 0.0.0.0 --port $PORT"