[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "mkdir -p /app/.venv",
    "python -m venv /app/.venv",
    "/app/.venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/app/.venv/bin/python -m uvicorn bot.main:app --host 0.0.0.0 --port $PORT"

# Explicitly disable Node.js
[phases.build]
cmds = ["echo 'Python app - no Node.js build needed'"]