[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.venv"]

[phases.install]
cmds = [
    "python -m venv /app/venv",
    "source /app/venv/bin/activate",
    "pip install -r requirements.txt"
]

[start]
cmd = "source /app/venv/bin/activate && python -m uvicorn bot.main:app --host 0.0.0.0 --port $PORT"