[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools"]

[phases.install]
cmds = [
    "python -m pip install --user -r requirements.txt"
]

[start]
cmd = "python -m uvicorn bot.main:app --host 0.0.0.0 --port $PORT"