[phases.setup]
nixPkgs = [
    "python311", 
    "python311Packages.fastapi",
    "python311Packages.uvicorn"
]

[start]
cmd = "cd /app && python -c 'import bot.main; print(\"Import successful\")' && python -m uvicorn bot.main:app --host 0.0.0.0 --port $PORT --log-level debug"