[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "mkdir -p $HOME/.local/bin",
    "export PATH=$HOME/.local/bin:$PATH",
    "python -m pip install --user -r requirements.txt"
]

[start]
cmd = "export PATH=$HOME/.local/bin:$PATH && python -m uvicorn bot.main:app --host 0.0.0.0 --port $PORT"